version: "3.3"

services:
  mysqldata:
    image: elestio/mysql:8.0
    restart: always

    command: /bin/true

  mysql:
    image: elestio/mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=huginn
      - MYSQL_USER=huginn
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./mysqldata:/var/lib/mysql

  web:
    image: elestio4test/huginn:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:4678:3000"
    environment:
      - DATABASE_NAME=huginn
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - APP_SECRET_TOKEN=${APP_SECRET_TOKEN}
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - HUGINN_DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - HUGINN_DATABASE_USERNAME=root
      - HUGINN_DATABASE_NAME=huginn
      - SMTP_USER_NAME=""
      - SMTP_PASSWORD=""
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=SMTP_ENABLE_STARTTLS_AUTO
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    depends_on:
      - mysql

  threaded:
    image: elestio4test/huginn:${SOFTWARE_VERSION_TAG}
    command: /scripts/init bin/threaded.rb
    restart: always
    environment:
      - DATABASE_NAME=huginn
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - APP_SECRET_TOKEN=${APP_SECRET_TOKEN}
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - HUGINN_DATABASE_PASSWORD=${ADMIN_PASSWORD}
      - HUGINN_DATABASE_USERNAME=root
      - HUGINN_DATABASE_NAME=huginn
      - SMTP_USER_NAME=""
      - SMTP_PASSWORD=""
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=SMTP_ENABLE_STARTTLS_AUTO
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    depends_on:
      - mysql
      - web

  pma:
    image: phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - "172.17.0.1:24581:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: huginn
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mysql
