version: '3.3'

services:
  mysqldata:
    image: mysql:5.7
    restart: always
  
    command: /bin/true

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - mysql.env
    volumes_from:
      - mysqldata

  web:
    image: huginn-test
    restart: always
    ports:
      - "172.17.0.1:3001:3000"
    env_file:
      - mysql.env
      - secrets.env
    depends_on:
      - mysql

  threaded:
    image: huginn-test
    command: /scripts/init bin/threaded.rb
    restart: always
    env_file:
      - mysql.env
      - secrets.env
    depends_on:
      - mysql
      - web